{% set name = "gct" %}
{% set version = "6.2.1629922860" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://repo.gridcf.org/gct6/sources/gct-{{ version }}.tar.gz
  sha256: bd1c12a918d8a505cb55e8ed4110e0fe49cfff7382a4be4f57b78f61af42daa3
  patches:
    - 0001-Fix-openssh-7.2p2-x11.patch-for-macOS.patch  # [osx]
    - 0001-Fix-TLS-1.3-gridcf-gct-196.patch
    - 0003-Ignore-unhandled-PEM-sequences.patch

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gct', max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
    - pkg-config
    - sed
  host:
    - openssl
    - zlib
    - libtool
    - libedit
  run:
    - perl
    # Seems well behaved
    # https://abi-laboratory.pro/?view=timeline&l=libtool
    - {{ pin_compatible("libtool") }}

test:
  commands:
    - ls -lah $PREFIX/bin
    - sleep 5
    - globus-domainname
    - globus-gass-cache -dirs
    # - which globus-gass-cache-destroy
    - globus-job-status -help
    - globus-gass-cache-util -help
    - globus-gass-server -help
    - globus-gass-server-shutdown -version
    - globus-hostname
    - globus-job-cancel -help
    - globus-job-clean -help
    - globus-job-get-output -help
    - globus-job-get-output-helper -help
    - globus-job-run -help
    - globus-job-submit -help
    - globus-makefile-header -help
    - globus-sh-exec -version
    # - which globus-url-copy
    - globus-version
    - globus-xioperf -help
    - globusrun -help
    - grid-ca-create -help
    - grid-ca-package -help
    - grid-ca-sign -help
    - grid-cert-diagnostics
    # - which grid-cert-info
    - grid-cert-request -help
    - grid-change-pass-phrase -help
    - grid-proxy-destroy -help
    - grid-proxy-info -help
    - grid-proxy-init -help
    - touch /tmp/example_file
    - gsiscp /tmp/example_file /tmp/example_file_123456
    - rm /tmp/example_file /tmp/example_file_123456
    # - which gsisftp
    # - which gsissh
    # - which gsissh-add
    # - which gsissh-agent
    - gsissh-keygen -f /tmp/examplekey -P asdadasdas

about:
  home: https://gridcf.org
  license: Apache-2.0
  license_family: Apache
  license_file: GLOBUS_LICENSE
  summary: 'Grid Community Toolkit'
  description: |
    The GCT is a nascent effort to provide community-based support for critical
    software packages for grid computing.

    The GCT is based on a fork of the Globus Toolkit but is not the Globus
    Toolkit. If you are interested in the Globus Toolkit, you can find it at
    http://toolkit.globus.org.
  dev_url: https://github.com/gridcf/gct/

extra:
  recipe-maintainers:
    - chrisburr
