travis:
  secure:
    BINSTAR_TOKEN: aU1/WoCx1zokWoryp20v0EkwRsgFr/blMPfY4Xk1WggxdjlhnMR2fUChHiilXIsfUIcMlYfgen34wTVMPdwdZxREC1RKVVSajlFVKupR06IsTeOXKpsnH4+Y0ArRxu6zLkax0MJc70W7kvOfDGdACX7qKppokg2w18d5TRTm/zMVIuid8Q/H/VtacJYwa9d7QriCAcM1EG/XJI1mCmol6EsnKX1yve2vv352wLws6mI5j6vvuDwdXrQhEh+++ZU0+KDZGWjYZx+C4DkCOhUb/xXwk2tF4wfBlZrLKX/7ORFqN8rjVaUmDDfknARavz+sMGK8XRImHBKwy+W4OFIDKNS+2SKoMyIHCmFqvAZpjQuKWwV+8AyDlbJunzC08ZO8VAulfiwhRFzYAdajWgLrVRMSCztwe8rcvjXLhVPpqKub2QTDfTdWRQWIMp1BbICkmUN8rNbT+yMOKtOdxbuMvFN+0zwtPfKU+WsRgAmlGHEkje8vRSffOSVLclXyWL0TrqDI7T9Bj0nG7shqUzjLGvQ9rZUPpPqW1SOe1wy8N7YRKsMfRtnWvEjqJzFzN4ynlFCZuvSMtFTWib+hZ/FvvwEojdhQmDbwkzwpEj4drC1vj/xoQlQFy3C7NBUxskvu2IW2WVijXPgIhrvN6V8+/sFJnz5eIbFg5OTucYKmMPw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
